language: php

php:
    - 7.2
    - 7.4

matrix:
    fast_finish: true

    include:
        -   php: 7.2
            env: PREFER_LOWEST=1

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

script:
    - find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

cache:
    directories:
        - $HOME/.composer/cache/

notifications:
    email: false
